### ISSUE TITLE
Ability to pass list of subnets or subnet prefix to support input from SLZ

### ISSUE THREAD

**Issue by Aashiq-J** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#141]
### Description

I'm also thinking that as part of this effort, we may want to give further flexibility in the ocp-base module. The ocp-base module takes a single input (the subnet name prefix) at the moment. The original support in landing-zone module support pointing to specific subnets by name (https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/main/patterns/roks/override.json#L33). So we may want to also allow pointing to specific subnet names. This could take the form of adding an extra parameter at https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/main/variables.tf#L45 that takes the list of subnet names. Either the prefix or the full list would be passed (but not both at the same time, module could add some logic errorring if both properties are set)

### Affected modules

[terraform-ibm-base-ocp-vpc](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
Context: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/pull/253#discussion_r1148146911

**Comment by Aashiq-J** [comment]
PR merged. Closing issue.
