### ISSUE TITLE
Expose ability to point to hpcs in different account for encryption

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#288]
### Description

Surface capability that is coming in next provider version - see https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4745

**Comment by ocofaigh** [comment]
Feature has been included in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.60.0-beta1 if you want to try it out @Ak-sky

**Comment by Ak-sky** [comment]
Released in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.12.0, closing this.
