### ISSUE TITLE
Add automated tests for OCP 4.11+4.12.

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#30]
### Description

See https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/15#discussion_r1118551459

### New or affected modules

- base-ocp-vpc

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by imprateeksh** [comment]
PR merged with the changes. Moving issue to closed.
