### ISSUE TITLE
Error: cannot list resource "pods" in API group

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#374]
### Affected modules

Consumer reporting this:

2024/02/23 16:05:59 Terraform apply | module.roks-cluster.null_resource.confirm_network_healthy[0]: Creating...
2024/02/23 16:05:59 Terraform apply | 2024-02-23T16:05:59.963Z [INFO]  Starting apply for module.roks-cluster.null_resource.confirm_network_healthy[0]
2024/02/23 16:05:59 Terraform apply | 2024-02-23T16:05:59.963Z [DEBUG] module.roks-cluster.null_resource.confirm_network_healthy[0]: applying the planned Create change
2024/02/23 16:05:59 Terraform apply | module.roks-cluster.null_resource.confirm_network_healthy[0]: Provisioning with 'local-exec'...
2024/02/23 16:05:59 Terraform apply | module.roks-cluster.null_resource.confirm_network_healthy[0] (local-exec): Executing: ["/bin/bash" "-c" ".terraform/modules/roks-cluster/scripts/confirm_network_healthy.sh"]
2024/02/23 16:05:59 Terraform apply | module.roks-cluster.null_resource.confirm_network_healthy[0] (local-exec): Running script to ensure kube master can communicate with all worker nodes..
2024/02/23 16:06:00 Terraform apply | module.roks-cluster.null_resource.confirm_network_healthy[0] (local-exec): Error from server (Forbidden): pods is forbidden: User "IAM#serviceid-XYZ" cannot list resource "pods" in API group "" in the namespace "calico-system"
2024/02/23 16:06:00 Terraform apply | module.roks-cluster.null_resource.confirm_network_healthy[0] (local-exec): Success! Master can communicate with all worker nodes.
2024/02/23 16:06:00 Terraform apply | module.roks-cluster.null_resource.confirm_network_healthy[0]: Creation complete after 0s [id=]

I suspect this is happening at https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/a01bdec4c1037f6ca2e57c750b584d6a329a7c53/scripts/confirm_network_healthy.sh#L12

Consumer state that serviceId has got necessary permission. Assuming this is correct, the issue could potentially be caused by delays in RBAC sync - would be good to double check if this lines is in the CI logs.

The other aspect is that the check does not happen if the kubectl get pods returns an error (but the message says success).

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
I don't think we should use the admin flag - I think there may be audit concerns with that. Instead I think the fix is either to add a retry to the first kubectl command with a sleep, as RBAC sync is usually ready in a matter of seconds

**Comment by vburckhardt** [comment]
Consumer is using admin flag - I think we should do the same. Admin config is pulled after auth on ibmcloud cli with an identity, so it should be possible to correlate if needed. If this becomes an issue from an audit perspective, some coordination would be needed around having that admin identity disabled through the ROKS stack, SCC scan tracking this, etc.
