### ISSUE TITLE
Adjust description for ingress hostname

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#416]
### Description

https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/684acb46a68a9755a2657886e3cc11f5662d4579/outputs.tf#L54

This is returning the subdomain however. Suggest to take the description from https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_cluster#ingress_hostname for now.

There is a separate ticket to change the output name https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5276 in provider. I think the module should change the name after the provider does to avoid confusion.

**Comment by Khuzaima05** [comment]
PR merged , closing this issue
