### ISSUE TITLE
Add operating-system input variable for OCP 4.15 and beyond (RHCoreOS now an option)

### ISSUE THREAD

**Issue by darrellschrag** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#429]
### Description
Add operating-system input variable as Red Hat CoreOS is now an option in OCP 4.15 and above.

### New or affected modules
all modules that create a ROKS cluster

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Khuzaima05** [comment]
PR merged, Closing this issue
