### ISSUE TITLE
ocp_entitlement should be null by default instead of the value cloud_pak

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#446]
A partner tried to use the basic examples. The provisioning failed because of the entitlement. Indeed, the basic example does not have not have the ocp_entitlement attribute specified. Thus, the value cloud_pak was used because it's by default. The default value should be null as most of the partners/client may want to start using ROKS with a Cloud Pak.

**Comment by Khuzaima05** [comment]
PR merged, Closing this issue
