### ISSUE TITLE
terraform-ibm-base-ocp-vpc docs is missing kubectl prereq

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#449]
https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc?tab=readme-ov-file#before-you-begin needs tobe updated to mention `kubectl` since its used by the `confirm_network_healthy` script

**Comment by lionelmace** [comment]
@ocofaigh I'm running the terraform script from terraform.io and kubectl cannot be installed, I believe.

**Comment by lionelmace** [comment]
Best would be to install kubectl in the script 

```
provisioner "local-exec" {
    command = "curl -LO [https://storage.googleapis.com/kubernetes-release/release/$(curl -s [https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl"
  }
```

and move it in the path (/usr/bin) to be safe.

**Comment by ocofaigh** [comment]
I don't think its a good idea to install dependant binaries as part of the module execution to the runtime, especially since it would also require public access which some consumers may not have. I think documented it as a required dependency is a fair ask.

**Comment by ocofaigh** [comment]
Doc updated in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/498
