### ISSUE TITLE
Missing the aspect about pool - https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_worker_pool#operating_system

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#460]
Missing the aspect about pool - https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_worker_pool#operating_system

_Originally posted by @vburckhardt in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/436#pullrequestreview-2122587555_

**Comment by imprateeksh** [comment]
Hi @vburckhardt @ocofaigh - This was done as part of PRs - [PR-467](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/467) and [PR-466](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/466). Hence closing the issue.
