### ISSUE TITLE
there should be a validation block here for the 2 possible values

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#461]
there should be a validation block here for the 2 possible values

_Originally posted by @vburckhardt in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/436#discussion_r1642621783_

**Comment by imprateeksh** [comment]
@vburckhardt @ocofaigh - This issue was resolved as part of [PR-466](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/466). Hence closing the issue.
