### ISSUE TITLE
Why is the Advanced examples only creating a public gateway in zone-1?

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#468]
Why is the Advanced example only creating a public gateway in zone-1? What are the motivation?

**Comment by vburckhardt** [comment]
That example is deploying across the 3 availability zones. The example is using the term "zone" for a construct different from the concept of availability zone. I think this is confusing, and should be changed. This can be done in this ticket.

**Comment by ocofaigh** [comment]
Addressed as part of https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/469
