### ISSUE TITLE
Error if csi block addon is removed

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#508]
│ Error: Invalid index
│ 
│   on ../../main.tf line 463, in locals:
│  463:     local.csi_driver_version != null ? { vpc-block-csi-driver = local.csi_driver_version[0] } : {}
│     ├────────────────
│     │ local.csi_driver_version is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.

**Comment by imprateeksh** [comment]
Closing the issue as now PR is merged.
