### ISSUE TITLE
Add example adding rules to the the kube-<clusterId> and kube-<vpcid> SGs

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#51]
### Description

Add an example that add custom rules to the kube-<clusterId> SG and kube-<vpcid> sg

1. Use https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_security_group to lookup the SG
2. Use https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_security_group_rule to add rule to SG

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
@imprateeksh - I think this one is complete? Should it be closed?

**Comment by imprateeksh** [comment]
@vburckhardt Thank you for mentioning this.
Yes this issue is completed hence marking it as closed.
