### ISSUE TITLE
Support for secondary storage on worker nodes

### ISSUE THREAD

**Issue by argeiger** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#520]
### Description

When you provision the Kubernetes cluster or create a new worker pool, you can add secondary storage to the nodes.  This is important for cp4d install since the images are very large.

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_cluster#secondary_storage
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/container_vpc_worker_pool#secondary_storage

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@argeiger This should be included in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.31.0
