### ISSUE TITLE
The latest version of the module does not support ocp_version "4.16"

### ISSUE THREAD

**Issue by KKooli** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#531]
### Affected modules

[

*](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc)

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Expected behavior

Creates the cluster with the latest version available 4.16

### Actual behavior

unsupported version

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

 Error: Invalid value for variable
│
│   on ocp-cluster.tf line 135, in module "ocp_base":
│  135:   ocp_version          = "4.16"
│     ├────────────────
│     │ var.ocp_version is "4.16"
│
│ The specified ocp_version is not of the valid versions.
│
│ This was checked by the validation rule at .terraform/modules/ocp_base/variables.tf:183,3-13.

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
We are working on adding this support. Thanks

**Comment by ocofaigh** [comment]
@KKooli Support has been added in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.32.0
