### ISSUE TITLE
Replace null resource block resetting the IKS apikey with provider resource

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#54]
In [terraform-ibm-base-ocp-vpc](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc) we currently use the ibmcloud cli to reset the apikey. But it looks like there is built in provider support for this https://registry.terraform.io/providers/IBM-Cloud/ibm/1.51.0/docs/resources/container_api_key_Reset

Can we ensure this works for VPC OpenShift cluster and if so replace the null resource block with provider resource?

**Comment by Aashiq-J** [comment]
Implementation was complete but, during the 10th Mar deep dive we decided on not using the reset resource as it makes things more complicated and we can't fully get rid of the reset script as the script does lot more tasks like checking if key already present and skip if present or reset if not.
