### ISSUE TITLE
Verify secondary storage feature is working

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#559]
Report from a consumer:

> Using the terraform-ibm-base-ocp-vpc module to create a ROKS cluster. I can't get the secondary storage option for a worker pool to work. It looks to me like the module is doing the right thing but maybe the underlying IBM Cloud provider is not working. Any ideas?
> provisioning completes with no errors and no secondary storage provisioned.

**Comment by toddgiguere** [comment]
I had verified that the extra storage feature was working in our `advanced` example and instructed consumer to have a look at that example to double-check their usage.

Consumer has verified that their usage was incorrect, and that the module is deploying secondary storage correctly.

Will close this issue.
