### ISSUE TITLE
Destroying fails trying to delete default worker pool

### ISSUE THREAD

**Issue by darrellschrag** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#560]
### Affected modules

ocp_base

*

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:
Terraform v1.6.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/external v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.16.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.33.0
+ provider registry.terraform.io/hashicorp/null v3.2.3
+ provider registry.terraform.io/hashicorp/random v3.6.3
+ provider registry.terraform.io/hashicorp/time v0.12.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.71.2

Your version of Terraform is out of date! The latest version
is 1.9.8. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform output

Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"ab8e2bd5-5076-4162-b2c8-a0b08edef6dd,ab8e2bd5-5076-4162-b2c8-a0b08edef6dd","code":"E1437","description":"The action cannot be completed because it would reduce the worker pool's size below the cluster's minimum requirement of 2 workers. If there are any worker operations pending, you might need wait for them to complete.","type":"BadRequest"}

### Expected behavior

Not sure this is possible with the way the terraform code is structured. The default (and other) worker pools are separate items. Creating the cluster that way seems to work, but when you delete worker pools you cannot leave the cluster without at least 2 workers. This causes the delete to fail.

### Actual behavior

Would like to be able to destroy the resources the module creates.

### Steps to reproduce (including links and screen captures)

Create a cluster using the module with 2 worker pools, one default and another one. Then destroy the created resources. The destroy will fail.

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@darrellschrag We have been working with several people from the IKS side on this. We have a workaround documented in the module which is all we can do until further improvements are made on the backend side. Please see https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc?tab=readme-ov-file#default-worker-pool-management

I'm going to close this issue, but if needed reach out internally for more info on future plans
