### ISSUE TITLE
Add kms boot volume encryption on default and additional worker pools

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#62]
### Description

Feature landed in terraform provider >= 1.42 . 

- Default worker pool: https://registry.terraform.io/providers/IBM-Cloud/ibm/1.51.0/docs/resources/container_vpc_cluster#example-with-boot-volume-encryption
- Other worker pools: https://registry.terraform.io/providers/IBM-Cloud/ibm/1.51.0/docs/resources/container_vpc_worker_pool#kms_instance_id

This comes in addition to existing support for encrypting secrets/etcd at https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/main/main.tf#L92

### New or affected modules

- [terraform-ibm-base-ocp-vpc](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Soaib024** [comment]
PR merged - hence closing
