### ISSUE TITLE
"zone" terminology is confusing and misleading

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#96]
The prefix at https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/main/variables.tf#L59 use the "zone-X" terminology. This is very prone to error as could be interpreted as "availability zones" when this actually denotes logical zones (segregation by subnet).

In fact, it seems that the examples are getting into this confusion - see https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/95

The default in the root module for worker_pools variable does not make sense either - as it is making assumptions on prefix on the subnets passed at https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/main/variables.tf#L34

**Comment by Aashiq-J** [comment]
PR merged. Closing issue
